---

- hosts: all
  become: true
  pre_tasks:

  - name:  update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true 
  tasks: 

 
  - name: add ssh key for samantha
    tags: always
    authorized_key: 
      user: samantha
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzApWKEEl9a3XyTya4Vwh8R6UCkuDJAasu1KeSznGyB7LfwPn/d5Yni42RJTTKehfe/K8nBokP59IvNP7Vwmo4RbvuzGlIIKc6WLyvZ4176nHRhKqxT2dFTNodIZyyF9TjRR6XN/0Y6RicCmIS9F6pN9SZxrkUH7UX/vfuseQRfkNRzTzXnFA/vuJLAFQg6qxeFSOLJPdCRgUhhV9DE8fdRI15jkrqZEDmJ5yPqLOnlv2Ft/XJ9gIUSYMrVlCTuoS42ipVbYVkSVkGpE1umAUF9Kn/2qpJXygaK4AYP1vUgAkhqcdJuh5qm03cjAWVeYjzwyuBlffzkV1gEhZ4L5IJl4QSMkp07Q8X+rJUIsLWMAe45HaqWaRIXAXNv/Gp/K6DFTtlLWq5y6mRhcSQqN//f/K8iLb8WCNgIGTpIQ8l3rdpBvOfK6yLHeKrdxSdxVjqbsc6VXvCjDLjzDBFL2gKNSOwsR+Rx0rsOLNarprAiJdV0q/Un2zjJUBB9n6lHvM= vagrant@master"

  
- hosts: workstations 
  become: true
  tasks:  

  - name: install unzip
    package: 
      name: unzip

  - name: install terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:     

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change email address for admin
    tags: apache,centos,httpd
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin test@test.com
    when: ansible_distribution == "CentOS"
    register: httpd
 
  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site 
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
 
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba 
    package:   
      name: samba
      state: latest
    

